### ISSUE TITLE
Parent change does not move service files under new parent

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [Jumpscale/ays9#111]
#### Installation information

- jumpscale version: 10744b3984bbfd26b9d72b41c863efbcef97aa3a
- ays version: f8f8bf5012e776f9bfd6b9aa6ffe88cb70ba64d3
- operating system: ubuntu 16.04 xenial

#### Detailed description

when running job.service.model.parentChange(<new parent service >) it only adjusts the data in the database and does not move the file to the correct location

#### Steps to reproduce

create a service with a actions.py run with so that it has a parent (parent 1 ) then in another action changeParent to another service instance  (parent 2)

#### Relevant stacktraces
NO Traceback

**Comment by abdulrahmantkhalifa** [comment]
old data appears when using ays restful api , the only way tp get the correct data is to reload the ays

**Comment by ahmedelsayed-93** [comment]
### software version
master : 47b1b4a
