### ISSUE TITLE
Wrong blueprint example in README of ovc.disk

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#115]
See: https://github.com/Jumpscale/ays9/tree/9.0.3/templates/disk/disk.ovc

This is a S3 example

**Comment by arahmanhamdy** [comment]
@yveskerwyn  The disk service is updated with new features and the full readme at 9.1.1 
https://github.com/Jumpscale/ays9/tree/9.1.1/templates/disk/disk.ovc

**Comment by arahmanhamdy** [comment]
After merging the 9.1.1 branch, you can find it now on master

**Comment by islamTaha12** [comment]
verified with 9.1.1
