### ISSUE TITLE
AYS rescheduling after failure

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/ays9#13]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description

When an actor fails the run is rescheduled. And a error level is added to know at which interval it should reschedule.
When the actor suceeds this level should be resseted so the rescheduling interval is lowered again

#### Steps to reproduce

have an actor that fails irregularly

**Comment by alichaddad** [comment]
should be fixed after https://github.com/Jumpscale/ays9/commit/efca064c1e1976c17c0ed43b23b670aa163f09ae
