### ISSUE TITLE
AYS service delete leaves uncleaned up references

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#133]
#### Installation information

- jumpscale version: 9.1.0

#### Expected behavior

![untitled diagram](https://user-images.githubusercontent.com/8425762/28817956-14210372-76aa-11e7-8fe1-770bd69b9a27.png)

Addresses https://github.com/zero-os/0-orchestrator/issues/587

**Comment by rkhamis** [comment]
Should trigger processChange on consumers of deleted services (if they're not deleted already to avoid re-creating those services)

**Comment by islamTaha12** [comment]
To delete a service, AYS will stop it then uninstall it then try to delete it, so in the case of it is an error in the delete step (cause it has been consumed),  This service will be stopped and uninstalled too which doesn't make sense .

**Comment by xmonader** [comment]
Should be fixed by https://github.com/Jumpscale/ays9/pull/159

**Comment by islamTaha12** [comment]
Re-open:
Dependence between parent and child has been messed up.
![image](https://user-images.githubusercontent.com/17981089/29132172-a730e034-7d2f-11e7-8dc8-07f0caadc81e.png)

**Comment by rkhamis** [comment]
Should be fixed by https://github.com/Jumpscale/ays9/pull/166

**Comment by ahmedelsayed-93** [comment]
### software version
master : 2d313e6b1b
