### ISSUE TITLE
Wrong service directory structure 

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/ays9#138]
#### Installation information

- jumpscale version: 9.1.0
- operating system: Ubuntu

#### Detailed description
Child services should be under parent directory in the file structure, instead they are on the same level as their parents under services directory.

#### Steps to reproduce
Execute a blueprint that have parent-child relation and check the file structure.

**Comment by ahussein** [comment]
Please enable the test https://github.com/Jumpscale/ays9/blob/master/tests/bp_test_templates/core/test_directory_structure.yaml after fixing this issue.

**Comment by islamTaha12** [comment]
Verified with JS 9.1.1 installed on ubuntu 16.04
