### ISSUE TITLE
Create special exception that can be raise from init/input to return badrequest to api

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/ays9#14]
#### Detailed description

Currently when raising exceptions during init or input it isnt possible to pass a proper exception to the ays api.

I would suggest that an `j.exceptions.Input` translates to a bad request.

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/ays9/commit/d376e07d127d8619a4b996d23318075a5e7a6edd

**Comment by islamTaha12** [comment]
@ashraffouda This pull fix a half of problem. It fix the issue from AYS but we have to fix it in orchestrator too

**Comment by islamTaha12** [comment]
@ashraffouda This pr changed the body but the status code still 500
![image](https://cloud.githubusercontent.com/assets/17981089/26826037/bb11eb5c-4ab7-11e7-8b1d-26e0b72b6f8d.png)
