### ISSUE TITLE
Expose job list of AYS actions

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/ays9#184]
#### Installation information

- jumpscale version: You tell me
- operating system: linux

#### Detailed description

we need a way to query the ays jobs please expose an API for this

**Comment by rkhamis** [comment]
We need a way to filter jobs on tags or something similar.

**Comment by rkhamis** [comment]
Still needs the tests, but can already be verified

**Comment by john-kheir** [comment]
Verified
