### ISSUE TITLE
Create a run with a callback_url doesn't call back

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#186]
#### Installation information

- jumpscale version: 9.1.1
- operating system: JS9 Docker Container

#### Detailed description

The run actually works, but the callback doesn't happen

#### Steps to reproduce

http://172.25.226.34:5000/ays/repository/ExyPhRgUVX0sUmR1GiEt/aysrun?callback_url=http://172.25.22.46:5001/api/partners/House%20Stark/customers/Eddard%20Stark/services/Drogon3

**Comment by yveskerwyn** [comment]
It still doesn't work as expected...

I've created a new run:
```shell
curl -X POST -H "Authorization: bearer $JWT" -H "Content-Type: application/json" http://$BASE_URL:$AYS_PORT/ays/repository/$REPO/aysrun?callback_url=$CALLBACK
```

When checking the status of the callback I see this:
```json
{"runid": "7bd4ddffded5a3a63557fc2d528d03a4", "runState": "ok"}
```

While when checking the status of the run with the the AYS command line tool:
```shell
(js9) root@js9:/optvar/cockpit_repos/test1# ays run list
run :2017/09/06 06:27:22 7bd4ddffded5a3a63557fc2d528d03a4 (running)
```

So the status is set to OK in the callback, immediately after creating the run...

**Comment by john-kheir** [comment]
Verified
