### ISSUE TITLE
Cover advanced routeros API in OVC 2.1.7

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/ays9#188]
A way to apply any custom configuration in RouterOS has been added to the OVC 2.1.7 api. This should be covered as well in the OVC templates.

part of #64

**Comment by arahmanhamdy** [comment]
Do you mean this endpoint:
`/cloudapi/cloudspaces/executeRouterOSScript` only? or there is other endpoints?

**Comment by rkhamis** [comment]
Yes

**Comment by john-kheir** [comment]
```ays repo destroy; ays blueprint test.yaml
repository destroyed
error during execution of the blueprint test.yaml: ERROR: No producer g8client found. Cannot continue init of service:vdc!cs1 ((type:ays.notfound)
```
that's because the "min:0" in the vdc config .. so either to change this or change the docs (as in the docs: the blueprint  doesn't have g8client param under the vdc service)

**Comment by john-kheir** [comment]
## Verified
