### ISSUE TITLE
Python client for AYS REST API

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#19]
A Python client for the AYS RESTful API that doesn't require to install JumpScale

We (used to) have this raml specifcation for the Cockpit API: https://github.com/Jumpscale/jscockpit/blob/master/ays_api/specifications/api.raml

If this raml still in sync with the REST API of the AYS9?

Is it easy to create an independent Python client based on this?

**Comment by xmonader** [comment]
For now you can use `pip3 install aysclient` :)
