### ISSUE TITLE
AYS9 Container Extra Port Listening 5000

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/ays9#193]
#### Installation information

- jumpscale version:

Core9

- operating system:

Ubuntu 16.04
#### Detailed description

Ideally the **js9_build** container command should also include a **5000 listening port** as that ideally would allow to Pass Calls to the Container, so it could run blueprints without the need of login into the container whenever you need to run any tasks.

**Comment by rkhamis** [comment]
Very nice idea, but only if AYS is being built.
