### ISSUE TITLE
Monitoring self-healing action should be done using run and not direct action call

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/ays9#204]
#### Installation information

- jumpscale version: 9.1.1
- operating system: linux

#### Detailed description
Currently in most of your implementation of the monitor actions, when we want to self-heal we just directly call an action from another service, instead we should create a run for the action and schedule the run. Like that the dependency tree is taken in account and all the producer action that need to be execute before the self-healing action are also executed.

Proposition is to add a method in AYS to easily schedule and add a run to the scheduler so it's easy for the actions to implement this flow.

signature of the method could be:
`scheduleAction(service, action)`
This method would set the stats of the action to schedule, check if the action of the producers are in error state, if yes also schedule them. Then create a new run and add it to the scheduler

**Comment by john-kheir** [comment]
It's working fine .. but the monitor doesn't start in the ays server unless it is restarted 
```
{
   "actionKey":"292c9315987f9adaaa3f499393c396c9",
   "errorNr":0,
   "isJob":true,
   "lastRun":1505828087,
   "log":true,
   "longjob":false,
   "name":"monitor",
   "period":60,
   "state":"error",
   "timeout":0
  },
```

**Comment by john-kheir** [comment]
Last comment .. Can't be reproduced again
