### ISSUE TITLE
Add callback to the install action of node.ovc

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#208]
#### Installation information

- jumpscale version: master
- operating system: JS9/Docker

#### Detailed description

When specifying a `callback_url` for a run, AYS only calls back once, which is immediately after creating the run, passing the following information:
{"runid": "b305b136b29db7903f1e11251f9dd294", "runState": "new"}

We'd like to have a second callback, in order to report back once all steps of the run are fully executed.

Since this new feature is requested specifically for a run that includes executing the `install` action of an `node.ovc` service, we'd could add an extra/new attribute to the `node.ovc` template `callbackURL`, which is then used in the `install` action to report back about the installation.

**Comment by alichaddad** [comment]
Callback can now be specified using the AYS cli as documented here:
https://github.com/Jumpscale/ays9/blob/master/docs/Commands/run/create.md

**Comment by yveskerwyn** [comment]
@alichaddad, thanks but this feature request is about also allowing to pass a callback url to the `node.ovc` service (new attribute), which then calls back when it has finished the creation of the VM

**Comment by john-kheir** [comment]
## Verified
