### ISSUE TITLE
service.model.producerRemove does not work 

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [Jumpscale/ays9#215]
#### Installation information

- jumpscale version: ays  9.1.1 on 620d435f5346aaed16c2b200140dcb026e98e7ef
- operating system: ubuntu xenial

#### Detailed description
using the the  ```service.model.producerRemove```  does not work 

#### Steps to reproduce
- consume service using another service then call service.model.producerRemove(consumned_service)
- print service.producers this will still have the consumed service 
- this appears if no ipdb is used as it might be a race condition

**Comment by john-kheir** [comment]
verified
