### ISSUE TITLE
Add failover() + basic monitor() actions to ovc.node

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#229]
#### Description

The failover() action should allow to move a VM to another G8 node.

With a basic monitor() action we should be able to trigger an event for which the failover() should be the event handler

We need this (in Russia) in order to start showing (demo + training) how self-healing works

**Comment by rkhamis** [comment]
Moving a vm to another G8 node is a cloudbroker action, meaning that only an administrator would be able to do it.

From my understanding this addresses endusers... and in this case it will only fail

**Comment by yveskerwyn** [comment]
Yes you are right @rkhamis 

Scenario is when a VM fails (for whatever reason). At that point you don't want OVC to automatically just restart the machine (on another node). You rather want that the workload (for instance a Docker container) gets properly restarted (or even reinstalled) too, and in order to have that work you'd need an AYS service for that workload. 

For AYS itself for instance, which is an example of such a workload, I've had many situations where VM hosting the JS9 docker had to be restarted manually, but that didn't bring the AYS server back... 

So a better FR might be to create an AYS template for AYS server, one that doesn't only installs, but also keeps it healthy, able to survive host reboots for instance...

**Comment by rkhamis** [comment]
I'm not sure I understand. You want an AYS server to monitor the AYS server?

**Comment by yveskerwyn** [comment]
Yep

**Comment by rkhamis** [comment]
In that case, I'll close this issue. Having a service deploy/install AYS somewhere else is another discussion altogether. I'd like to first have all jumpscale modules be pip installable to make it absolutely clean.

Thanks Yves
