### ISSUE TITLE
Unable to destroy repo with longjobs

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/ays9#237]
#### Installation information

- jumpscale version:master(c277ddbc)
- operating system:Ubuntu

#### Detailed description
An ays repo with a long job isn't properly destroyed. The services and actors directory are created again and the long job is restarted when the ays is restarted.

#### Steps to reproduce
- Create a repo with a long job
- Destroy the repo
- Check the directories in the repo which will still have services and actors directories.
- Restart the ays server and the job will restart

**Comment by john-kheir** [comment]
Verified
