### ISSUE TITLE
ays auto consume incorrect behavior

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/ays9#239]
#### Installation information

- jumpscale version:master(9.1.3)
- operating system:Ubuntu

#### Detailed description
If an actor has a consumer relationship not set to auto and the minimum producing services don' t exist and didn't specify the service that it will consume in the blueprint it will consume service with same actor if it exists.

#### Steps to reproduce
In your actor template set a consumer relationship and set auto to false with minimum of one service. Create a service from the actor that willl be the producer independent of the consuming service and then create the consuming service without specifying the producing service. It will consume the service created even though the correct behavior is raising an error detatiling that the min number of producing services isn't met.

**Comment by john-kheir** [comment]
## Verified
