### ISSUE TITLE
Adding new entry in template schema not reflected in service model

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/ays9#241]
#### Installation information

- jumpscale version:9.1.2
- operating system:Ubuntu

#### Detailed description
After adding new entry in the actor template `schema.capnp`, the new parameter isn't reflected in the service model unless it is explicitly given a value. The change however is reflected in the actors directory of the repo.

#### Steps to reproduce
Add new parameter and execute `ays actor update` it will be reflected in the actors directory but if checked using `ays service show` the new parameter won't be there unless it is given a value. Which means the service model data isn't being updated.

**Comment by rkhamis** [comment]
Already fixed
