### ISSUE TITLE
Cleanup non-test actors from tests directory

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/ays9#287]
The current test services in the repo are not all used for testing. They are leftover from the 8.x version, we should clean them up and only keep the used test services.

**Comment by ahussein** [comment]
https://github.com/Jumpscale/ays9/pull/288

**Comment by rkhamis** [comment]
Yes, that and we need to not test using vdcfarm and sshkey.

We should create our own test templates instead of using actual templates that could change for any reason

**Comment by ahussein** [comment]
hmm, I am not sure how changing the template we are using is related to removing the non-used actors?

**Comment by rkhamis** [comment]
They're not actually test services either. Related in the larger scheme of things.
