### ISSUE TITLE
AYS actor update doesn't update schema properly

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/ays9#289]
#### Installation information

- jumpscale version: master
- operating system: linux

**Comment by rkhamis** [comment]
@zaibon Is this the same as https://github.com/Jumpscale/ays9/issues/262? or do you mean something different?
This is not very informative

**Comment by zaibon** [comment]
No that's not the same thing.
I need to gather detail information about the issue. open it to not forget about it.

**Comment by zaibon** [comment]
I know we had the case multiple time where an actor update didn't work properly and nothing tells you about it.

I know 2 cases:
- there is a bug in the `actions.py` that prevent the code to be updated properly. No error message during update
- there is a new element in the schema. Sometime it's impossible to get the new attribute in the schema. Again no error.

These are the 2 cases I can remember right now.

**Comment by rkhamis** [comment]
The second one for sure doesn't happen if your data is correct. I just validated it.

The first one, I'll need more information about. Let's keep it open to test all cases anyway.

**Comment by zaibon** [comment]
> The second one for sure doesn't happen if your data is correct. I just validated it.

But do we have a clear error message the explain the problem ?
