### ISSUE TITLE
Support deploying AYS Portal in remote/seperate container

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#306]
Add parameters to the AYS Portal `config.yaml` for IP address and port number of the AYS Server RESTful API in order to support the below setup, allowing the portal to run in a separate container:

![screen shot 2017-10-08 at 14 29 17](https://user-images.githubusercontent.com/13795109/31316791-e747e468-ac34-11e7-86fe-de5a1fc70b66.png)

**Comment by ahmedelsayed-93** [comment]
### software version 
9.2
