### ISSUE TITLE
get full template's role when getting or finding

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/ays9#307]
#### Installation information

- jumpscale version: master
- operating system: Ubuntu 16.04

#### Detailed description
I have two templates `storagecluster.block` and `storagecluster.object` while listing services under `storagecluster` it gets me both of the services under the same role also the same behaviour for getService which **what I want**. But when I inspected `service.role` all I can find is `storagecluster`, i even checked `service.path` and it was `services/storagecluster/{servicename}`. I want a way to get the child/specific role type from the service I got.

**Comment by rkhamis** [comment]
- Filter on role and actorname when list services.
 - show actorname in the service view

**Comment by khaledkbadr** [comment]
@rkhamis I found out that serviceFind filter on actor name if I passed `role = role.actorname` so I think that part is already done

**Comment by rkhamis** [comment]
@khaledkbadr serviceFind is internal to the ays lib. API-wise you wouldn't be able to access it.
