### ISSUE TITLE
Ays shows tests passed even if the test contains an error 

### ISSUE THREAD

**Issue by ashraffouda** [Jumpscale/ays9#365]
#### Installation information

- jumpscale version: 9.2.0
I put a syntax error in the test and ran the test I found ays shows an error and the test shows it is passed !!!
How to reproduce 
1- try to but a syntax error in any of the actor test like this one `test_longjobs_actions!` 

![screenshot from 2017-11-01 15-36-07](https://user-images.githubusercontent.com/1689456/32277273-90aed49c-bf1a-11e7-8bff-760800536e5e.png)

2- run the test 
```
from ays_testrunner.testrunner import AYSTestRunnerFactory 
runner = AYSTestRunnerFactory.get(name='custom', config={'bp_paths': ["/opt/code/github/jumpscale/ays9/tests/bp_test_templates/core/test_longjobs.yaml"]})
 runner.run()
```
2- out put is 
Current state of the run:
```
RUN:aad10759ec9075052eb721463e031e73 (error)
step:1 (ok)
- test_longjobs_actions     tlj                            | install         (ok)
step:2 (error)
- test_longjobs_actions     tlj                            | test            (error)

[Wed01 13:33] - testrunner.py       :44  :j                              - DEBUG    - Validating response status code 200 with expected status code 200
[Wed01 13:33] - testrunner.py       :44  :j                              - DEBUG    - Validating response status code 200 with expected status code 200
[Wed01 13:33] - testrunner.py       :44  :j                              - DEBUG    - Validating response status code 200 with expected status code 200
[Wed01 13:33] - testrunner.py       :44  :j                              - DEBUG    - Validating response status code 200 with expected status code 200
AYS testrunner results
---------------------------

Total number of tests: 1
Number of passed tests: 1
Number of failed/error tests: 0
```

although the action test shows an error !!!
![screenshot from 2017-11-01 15-35-04](https://user-images.githubusercontent.com/1689456/32277372-edc45616-bf1a-11e7-8d2e-47048f7010e6.png)

this issue is different from https://github.com/Jumpscale/ays9/issues/360 in that this issue ays didn't crashed

**Comment by ahussein** [comment]
I found the problem and its only affecting the sequential test runner both the threaded and parallel runners are not affected with this bug.
