### ISSUE TITLE
Remove ays9 repo dependency for AYS Portal app 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#367]
#### Installation information

- jumpscale version: 9.2
- operating system: Ubuntu

#### Detailed description

Currently to install AYS Portal as shown in the below picture, you also need the ays9 repo on the VM running the AYS Portal:

![screen shot 2017-11-02 at 10 00 53](https://user-images.githubusercontent.com/13795109/32318639-23a8c88c-bfb8-11e7-86ad-6c4de579bc88.png)

This is because the Portal requires access to the baseurl parameter in the RAML file of the AYS Server: https://github.com/Jumpscale/ays9/blob/master/JumpScale9AYS/ays/server/apidocs/api.raml#L3

Instead create a `config.yaml` specific to the AYS Portal app, containing all AYS Portal app configuration, including the address of the AYS Server API endpoint.

**Comment by ahmedelsayed-93** [comment]
### software version 
9.2
