### ISSUE TITLE
Unable to configure remote AYS Server from AYS Portal

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#371]
#### Installation information

- jumpscale version: 9.2.0 (master)
- operating system: Ubuntu

#### Detailed description

Updating  `/opt/code/github/jumpscale/ays9/apps/AYS/.space/nav.wiki` in order to redirect the AYS API Console in the AYS Portal works:
-> AYS API:https://ays.vreegoebezig.be:5000/apidocs/index.html?raml=api.raml

**However** updating `baseUrl` in `/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/apidocs/api.raml` to the same AYS Server RESTful API endpoint doesn't allow to show the remote repositories in the AYS Portal:

![screen shot 2017-11-03 at 16 42 17](https://user-images.githubusercontent.com/13795109/32382598-fc93ee4e-c0b5-11e7-8085-db9fa6350276.png)

#### Check the server

https://se-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1227
ssh -A root@195.143.34.162 -p8022

**Comment by ahmedelsayed-93** [comment]
verified 
using this docs https://github.com/Jumpscale/ays9/tree/master/docs/AYS-Portal/installation#install-ays-and-the-ays-portal

### software version 
9.2
