### ISSUE TITLE
Colliding actions nullify each other

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/ays9#376]
#### Installation information
- jumpscale version: 9.2
- operating system: Ubuntu

#### Detailed description
My scenario goes as following:
- I have a service with an error in the `install` action
- Then I closed my ays server (don't know if that's relevant though)
- I then execute blueprint with a delete in its action for that service
- When I execute `ays run create -f`, I can see that `ays` is trying to reschedule the failed `install` action even though I want to `delete` and clearly the `delete` action here has the highest priority

### Suggested way to fix that 
- Add a way to configure actions priorities (maybe in the service's config file), for example for that service I want to make the `delete` action with the highest priority. So when the delete action is issued all the other actions that're scheduled get thrown under the bus.

**Comment by rkhamis** [comment]
Perhaps we could instead always give priority to the last desired action, unscheduling previously scheduled actions.

**Comment by zaibon** [comment]
Let's  not try to patch this in a dirty way. This problem is known and need to be fixed by improving how AYS deals with this kind of case. Should be dealt in the next iteration of AYS

**Comment by despiegk** [comment]
a new version of ays fixes this
