### ISSUE TITLE
AYS Portal showing more AYS repositories that are not on disk in under cockpit_repos

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#377]
#### Installation information

- jumpscale version: 9.2.0
- operating system: Docker container on Ubuntu 16.04

#### Detailed description

When comparing the list of repositories in the AYS Portal you see some repositories which are not on disk, or at least not in the `cockpit_repos` directory:

- All the repo's starting with `sample_` in their name
- `kvm_packet.net`
- `docker.ovc`
- `3JG8NoDaK3r4mDP0yk5N`
- `eWi49Kq28VtJ1OdA0ukm`
- `j2UDMzdozXlOehpVSGV4`

#### Steps to reproduce

AYS Server + Portal is running in a Docker container on https://mr4.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1919

- AYS Server:
  - `ssh -A root@185.193.143.74 -p2022`
  - Check the Docker container

```bash
root@portal9:/host/var/cockpit_repos# ls -1
jH4ZdNb9uHkeEoF7Walk
test
wim
Y8RheqNiR7WMEirGxlIh
yves
````

- AYS Portal: http://185.193.143.74:8200

![screen shot 2017-11-10 at 14 33 39](https://user-images.githubusercontent.com/13795109/32660740-4e2cd95a-c624-11e7-8962-e0970c2d36db.png)

**Comment by rkhamis** [comment]
Cockpit repos can be anywhere under /opt/code or /var/cockpit_repos... shown here are the test repos, which are valid AYS repos.
