### ISSUE TITLE
Method to update the baseUri in RAML file

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#378]
#### Installation information

- jumpscale version: 9.2.0

#### Detailed description

When you install AYS server it comes with an AYS API Console that is configured to work on local host, in order to change that you need to update the value of `baseUri` in `/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/apidocs/api.raml`

Create a method for this so it can be done programatically:
`j.tools.prefab.local.apps.atyourservice.baseurl_update(url="http://localhost", port=5000)`

**Comment by rkhamis** [comment]
Unneeded. @ashraffouda will link docs

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/ays9/blob/master/docs/AYS-Portal/installation/README.md#install-ays-and-the-ays-portal

**Comment by yveskerwyn** [comment]
Reopening since the proposed `prefab.js9.atyourservice.configure_portal(host='http://172.17.0.5', port="5000")` is related to the AYS Portal, while the AYS API Console doesn't require the AYS Portal.

**Comment by khaledkbadr** [comment]
Will close in favour to https://github.com/Jumpscale/prefab9/issues/99
