### ISSUE TITLE
Method to update the value of AYS API in nav.wiki (AYS Portal app)

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#380]
#### Installation information

- jumpscale version: 9.2.0

#### Detailed description

When you install the AYS Portal app the link to the AYS API Console that is configured to redirect to on localhost, in order to change that you need to update the value of `AYS API` in `/opt/code/github/jumpscale/ays9/apps/AYS/.space/nav.wiki`

The default is `http://localhost:5000/apidocs/index.html?raml=api.raml`

Create a method for this so it can be done programatically:
`j.tools.prefab.local.apps.atyourservice.aysapiconsole_update(url="http://localhost", port=5000)`

**Comment by khaledkbadr** [comment]
Will close in favour to https://github.com/Jumpscale/prefab9/issues/99
