### ISSUE TITLE
j.tools.prefab.local.apps.atyourservice.stop() doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#381]
#### Installation information

- jumpscale version: 9.2.0

`j.tools.prefab.local.apps.atyourservice.stop()` doesn't stop the running AYS server

**Comment by ahussein** [comment]
@yveskerwyn  How did you start the ays server. Did you use j.tools.prefab.local.apps.atyourservice.start() ? or something else ?
