### ISSUE TITLE
AYS Portal requires AYS client from AYS repo

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#401]
### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu
- VM: https://se-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1823
- SSH `ssh root@195.143.34.166 -p2201`

#### Detailed description

In order to create the below setup also the jumpscale/ays9 repo needs to be cloned on VM-2, which was achieved with `portal_host.prefab.tools.git.pullRepo("https://github.com/Jumpscale/ays9.git", branch="master")`. As it turns out this is not enough since the AYS portal relies on the AYS client from this repository, instead of using the AYS client as available in jumpscale/lib9.

We need to update the AYS portal code so it uses the jumpscale/lib9 client, which is documented here: https://github.com/Jumpscale/lib9/blob/master/docs/Howto/AYS_client.md#auto-generated

![screen shot 2017-12-12 at 09 14 30](https://user-images.githubusercontent.com/13795109/33873888-03bbc518-df1d-11e7-9240-ef239ff0e8d9.png)

See the below stack trace when trying to start the portal with the AYS portal app ("Cockpit") loaded.

#### Steps to reproduce

VM-2 was provisioned as follows:
```
portal_host = vdc.machine_create(portal_host_name, "mykey", sizeId=3)
portal_host.prefab.system.ssh.authorize("cloudscalers", pubkey.model["publickey"])
portal_host.prefab.system.ssh.authorize("root", pubkey.model["publickey"])
portal_host.prefab.js9.js9core.install(branch='master')
portal_host.prefab.tools.git.pullRepo("https://github.com/Jumpscale/ays9.git", branch="master")
portal_host.prefab.web.portal.install(False)
portal_host.prefab.web.portal.start()
portal_host.portforward_create(80, 8200)
portal_host.prefab.js9.atyourservice.load_ays_space()
portal_host.prefab.web.portal.stop()
portal_host.prefab.web.portal.start()
portal_host.prefab.js9.atyourservice.configure_portal("http://{}".format(public_ip_address), 5000)
```

#### Relevant stacktraces

Orginaly a non-related stack trace was provided that got moved into https://github.com/Jumpscale/portal9/issues/99

We'll have to re-run the script in order to check for a related stack trace:

```bash
  ...
```

**Comment by arahmanhamdy** [comment]
duplicates jumpscale/portal9#91
