### ISSUE TITLE
Unable to get the auto-push to work with Gitea

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#415]
#### Installation information

- jumpscale version: 9.2.1
- operating system: Ubuntu

#### Detailed description

We get an error in the tmux window: `user root doesn't exist`.

**Comment by rkhamis** [comment]
This ticket really doesn't say much.


@yveskerwyn Could you describe a bit more what you were doing, the steps you took.... etc?

**Comment by yveskerwyn** [comment]
Let's close since this was related to AYS not being able to auto-push repo changes to a central Gitea server
