### ISSUE TITLE
AttributeError: 'Bash' object has no attribute 'locale_check'

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#417]
#### Installation information

- jumpscale version: 9.2.1
- operating system: Ubuntu 16.04
- AYS Server: https://be-gen-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=299
- SSH: `ssh -A root@195.134.212.38 -p7122`

#### Detailed description
After having updated all repositories (pull) and executed `js9_init` trying to restart AYS server fails with `AttributeError: 'Bash' object has no attribute 'locale_check'`

![screen shot 2018-02-06 at 13 51 37](https://user-images.githubusercontent.com/13795109/35860807-b550b0e6-0b45-11e8-9cff-6b05530272aa.png)

**Comment by arahmanhamdy** [comment]
please use 9.2.1 branch
