### ISSUE TITLE
Make it possible to trigger an action with job arguments

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/ays9#44]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description

It would be nice that when triggering an action from a blueprint it would also be possible to pass it some job arguments.

**Comment by rkhamis** [comment]
You're thinking about this the wrong way. A service is not a lib.
As discussed earlier, this FR isn't in line with AYS logic.

Service should have an arg that you change and handle in your service.
