### ISSUE TITLE
Add attribute to attach VM to external network

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#62]
Related to https://github.com/Jumpscale/ays9/tree/master/templates/nodes/node.ovc

Allowing to create a VM that gets attached the external network of the VDC.

This was discussed/promised to the Artilium team building the e-portal.

**Comment by rkhamis** [comment]
Part of https://github.com/Jumpscale/ays9/issues/64

**Comment by rkhamis** [comment]
Duplicate of https://github.com/Jumpscale/ays9/issues/79
