### ISSUE TITLE
VM template to attach to external nw/detach external nw *

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#79]
#Corresponds to API: 
 - /cloudapi/machines/attachExternalNetwork (will attach to VDC's external network)
 - /cloudapi/machines/detachExternalNetwork

Docs and tests must be included

part of #64 

For supported virtual machine images (ubuntu / redhat), the blueprint also needs to try to statically configure the provisioned external ipaddress into the vm and bring up the interface.

**Comment by rkhamis** [comment]
Blocked on https://github.com/0-complexity/openvcloud/issues/861 and https://docs.greenitglobe.com/openvcloud/openvcloud/issues/50

**Comment by rkhamis** [comment]
After discussion with @grimpy , this is by design.

**Comment by ahmedelsayed-93** [comment]
### software version
master 4ab35d89
