### ISSUE TITLE
AYS API: GetServiceByName returns service if you filter on incorrect parent

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/ays9#8]
#### Installation information

- jumpscale version:
8.2
- operating system:
Ubuntu

#### Detailed description
If you try to get service by name from ays and give it an incorrect parent in the query params, it returns the service and ignores the incorrect filtering instead of 404.

#### Steps to reproduce
GET http://172.17.0.3:5000/ays/repository/objstor/service/gateway/mygw?parent=node.g8os!5254003456

Where node '5254003456' doesn't exist but mygw exists and has another parent node. The api returns the mygw service normally.

**Comment by xmonader** [comment]
I don't see parent as query param in getServiceByName, but It's there is listServicesByRole https://github.com/Jumpscale/ays9/blob/master/JumpScale9AYS/ays/server/apidocs/api.raml#L537
