### ISSUE TITLE
Disk template to create/delete/list/limit IO of disk

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays9#84]
Corresponds to API: 
 - /cloudapi/disks/list
 - /cloudapi/disks/limitIO
 - /cloudapi/disks/create
 - /cloudapi/disks/delete

Docs and tests must be included

part of #64

**Comment by ahmedelsayed-93** [comment]
### software version
master : 47b1b4a

### blueprints
https://github.com/Jumpscale/ays9/tree/master/templates/disk/disk.ovc
