### ISSUE TITLE
No way not to specify max services consumed by another

### ISSUE THREAD

**Issue by mie00** [Jumpscale/ays9#94]
#### Installation information

- jumpscale version: 9
- operating system: Ubuntu xenial

#### Detailed description

I want to specify as many services as possible to be consumed from another.

When I discarded max attribute it gave me a key error.

So for now I am putting max as a very high number, but it would be better if there is a way to be able to say there is no max.

#### Steps to reproduce

Discard max from config.yaml

#### Relevant stacktraces

```python
File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Actor.py", line 197, in _initProducers  
max=int(consume_info['max']),
```

**Comment by islamTaha12** [comment]
I created a schema with no max and with min: 1, then consumed 3 services.
```bash

RUN:c1c6b4278322cfc8b75663b2a8ae6046 (ok)
step:1 (ok)
- consumer.parent           p                              | install         (ok)
step:2 (ok)
- consumer.child            c                              | install         (ok)
- consumer.child            c1                             | install         (ok)
- consumer.child            c2                             | install         (ok)
step:3 (ok)
- consumer.consumer         cc                             | install         (ok)

```
